/* ============================================================
   data.js — Sales dataset
   Author: Abhishek Sharma | Data Analyst Portfolio
   ============================================================
   In a real project, this would be fetched from a REST API
   or generated by a Python/SQL backend.
   ============================================================ */

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun',
                 'Jul','Aug','Sep','Oct','Nov','Dec'];

/* Monthly revenue (in $000s) and targets, by year + region */
const SALES_DATA = {
  2024: {
    all: {
      revenue: [420, 385, 510, 475, 560, 620, 590, 680, 710, 650, 720, 810],
      target:  [400, 420, 480, 500, 540, 600, 580, 650, 700, 680, 710, 800]
    },
    north: {
      revenue: [120, 110, 145, 130, 160, 175, 168, 192, 201, 184, 205, 230],
      target:  [115, 120, 138, 142, 154, 171, 165, 185, 200, 194, 202, 228]
    },
    south: {
      revenue: [100, 90, 122, 115, 134, 148, 141, 163, 170, 156, 172, 194],
      target:  [ 96, 100, 115, 120, 130, 144, 139, 156, 168, 163, 170, 192]
    },
    east: {
      revenue: [110, 105, 138, 128, 152, 167, 160, 183, 192, 176, 196, 218],
      target:  [105, 115, 132, 136, 146, 163, 157, 176, 190, 184, 192, 215]
    },
    west: {
      revenue: [90, 80, 105, 102, 114, 130, 121, 142, 147, 134, 147, 168],
      target:  [84,  85,  95, 102, 110, 122, 119, 133, 142, 139, 146, 165]
    }
  },
  2023: {
    all: {
      revenue: [360, 340, 430, 410, 480, 530, 510, 590, 620, 580, 640, 720],
      target:  [350, 370, 420, 440, 470, 520, 500, 570, 610, 600, 630, 710]
    },
    north: {
      revenue: [103, 98, 123, 117, 137, 151, 146, 168, 177, 165, 182, 205],
      target:  [100, 106, 120, 126, 134, 149, 143, 163, 174, 171, 180, 203]
    },
    south: {
      revenue: [86, 82, 103, 98, 115, 127, 122, 141, 149, 139, 153, 172],
      target:  [84, 89, 101, 106, 113, 125, 120, 137, 146, 144, 151, 170]
    },
    east: {
      revenue: [94, 90, 119, 110, 131, 144, 139, 158, 166, 151, 169, 188],
      target:  [91, 99, 114, 117, 127, 141, 136, 153, 163, 158, 166, 185]
    },
    west: {
      revenue: [77, 70, 85, 85, 97, 108, 103, 123, 128, 125, 136, 155],
      target:  [75, 76, 85,  91,  96, 105, 101, 117, 127, 127, 133, 152]
    }
  }
};

/* Category split (fixed; for doughnut chart) */
const CATEGORY_DATA = {
  labels: ['Software', 'Hardware', 'Services', 'Training'],
  values: [38, 22, 28, 12],
  colors: ['#4B3C8C', '#1D9E75', '#378ADD', '#BA7517']
};

/* Top products table */
const PRODUCTS = [
  { name: 'Analytics Pro',   revenue: 248000, units: 1240, margin: 62, targetPct: 94  },
  { name: 'DataViz Suite',   revenue: 196000, units:  980, margin: 58, targetPct: 88  },
  { name: 'BI Dashboard',    revenue: 172000, units:  860, margin: 71, targetPct: 103 },
  { name: 'CRM Connect',     revenue: 148000, units:  740, margin: 49, targetPct: 79  },
  { name: 'Report Builder',  revenue: 124000, units:  620, margin: 54, targetPct: 91  },
  { name: 'ETL Pipeline',    revenue: 108000, units:  540, margin: 66, targetPct: 97  },
  { name: 'Cloud Connector', revenue:  94000, units:  470, margin: 60, targetPct: 85  }
];

/* Chart color palette */
const PALETTE = {
  purple: '#4B3C8C',
  teal:   '#1D9E75',
  amber:  '#BA7517',
  coral:  '#D85A30',
  blue:   '#378ADD',
  gray:   '#B4B2A9'
};

const REGION_COLORS = {
  north: PALETTE.purple,
  south: PALETTE.coral,
  east:  PALETTE.blue,
  west:  PALETTE.amber
};
